### ISSUE TITLE
Don't show team options when you aren’t on a team subscription

### ISSUE THREAD

**Issue by jasonzurita** [pointfreeco/pointfreeco#297]
When a user has an individual subscription, and that user clicks to remove themselves from their own team, that user will disassociate their subscription from themselves - i.e., lose their subscription. The remove option should either be changed or removed to prevent accidentally losing a subscription (like I did 😬).

---

![screen shot 2018-08-15 at 3 19 59 pm](https://user-images.githubusercontent.com/13800855/44168493-794af580-a09f-11e8-9a26-9e103413cad6.png)

**Comment by mbrandonw** [comment]
Good find, we'll have a fix soon!

**Comment by mbrandonw** [comment]
It's pretty small effort. I'll give a few hints and if yer down to try then please do!

* This is the view that renders that lil fragment of HTML.
https://github.com/pointfreeco/pointfreeco/blob/48e85043005966cefb871b1622a12d29e5f24760/Sources/PointFree/Account/Account.swift#L538-L556

* That view is rendered inside this view, which stacks all of the team subscription related stuff on top of each other:
https://github.com/pointfreeco/pointfreeco/blob/48e85043005966cefb871b1622a12d29e5f24760/Sources/PointFree/Account/Account.swift#L325-L346

* And finally that view is rendered inside this view, which does the logic to check if it's the subscription owner viewing this page or not:
https://github.com/pointfreeco/pointfreeco/blob/48e85043005966cefb871b1622a12d29e5f24760/Sources/PointFree/Account/Account.swift#L314-L323

* The bug is that we only check `data.isSubscriptionOwner`, but what we really want to check is if the user is the owner of the subscription _and_ the subscription is a team subscription. Individual subscriptions can just fallthrough to the next conditional.

* That `isSubscriptionOwner` helper is defined here, and so we just need a new helper to describe the logic that we actually want:
https://github.com/pointfreeco/pointfreeco/blob/48e85043005966cefb871b1622a12d29e5f24760/Sources/PointFree/Account/Account.swift#L767-L769

If you end up fixing this bug you will also need to fix the tests. That should mean just running the `AccountTests` in record mode and verifying that everything looks correct. 

Wanna give it a shot?

**Comment by jasonzurita** [comment]
This is such a great breakdown, thanks. I will start digging into this and give it a shot!

With that said, I am sure you would be able to fix this a lot faster than that I will be able to, so please don't let me hold you back from getting this fixed sooner.

**Comment by mbrandonw** [comment]
nahhh, we can wait at least a few days to fix this. the bug has been there awhile, and yer the first to click that remove button 😂

**Comment by jasonzurita** [comment]
Haha, my damn curiosity...

And, sounds good, I will give it a shot!

**Comment by jasonzurita** [comment]
@mbrandonw Is there a way to locally fake a logged-in user with a subscription for testing. Maybe by manipulating the [current environment](https://github.com/pointfreeco/pointfreeco/blob/fa6ffd6f5e4b523e1da9e968e458af21ffbf7351/Sources/PointFree/Environment.swift#L6)?

**Comment by mbrandonw** [comment]
Hey @jasonzurita, I initially thought that would have been possible (manipulating the current environment), but looks like there's a bit of prep work that needs to be done first. The best way to edit the environment is using `PointFreeTestSupport` lib, which is what we do in tests and playgrounds. However, there's a hidden dependency on `XCTest` in that lib, and that prevents you from building and running the actual server.

So, until I can do a lil work disentangling that, I'd say the way to test this is to just generate new test screenshots and make sure it looks how you expect, or you could run the page in the following playground: https://github.com/pointfreeco/pointfreeco/blob/master/PointFree.playground/Pages/Account.xcplaygroundpage/Contents.swift

**Comment by jasonzurita** [comment]
@mbrandonw Ahhh, snapshots and playgrounds to the rescue! Sounds like a good substitute, thanks.

**Comment by jasonzurita** [comment]
@mbrandonw A few questions if you don't mind:

- What is the difference between `Database.Subscription` and `Stripe.Subscription`? Is one used mainly as a fallback?
- In determining if a user is part of a team subscription, my first thought was to check the number of teammates, but that felt dirty. I am leaning towards something like:
  ```
  stripeSubscription?.plan.id == Tagged.teamYearly || stripeSubscription?.plan.id == Tagged.teamMonthly
  ```
  What are your thoughts on this? Also, your answer to my first question may impact this as there is a plan on the database subscription too.
- Finally, I am not sure if simply adding the above `isTeamSubscription` helper to the
https://github.com/pointfreeco/pointfreeco/blob/6da8acb583b22005053b617c265ded2a05cf722f/Sources/PointFree/Account/Account.swift#L316
check and just falling through to the next conditional will yield a desirable result. I tested it out and the resulting fall through conditionals yield the below screens. I am leaning towards something like adding the `isTeamSubsubscription` to this guard. Thoughts?
https://github.com/pointfreeco/pointfreeco/blob/6da8acb583b22005053b617c265ded2a05cf722f/Sources/PointFree/Account/Account.swift#L539

---

### First conditional
https://github.com/pointfreeco/pointfreeco/blob/6da8acb583b22005053b617c265ded2a05cf722f/Sources/PointFree/Account/Account.swift#L319

<img width="399" alt="screen shot 2018-08-21 at 9 18 29 am" src="https://user-images.githubusercontent.com/13800855/44403884-8a728700-a523-11e8-8c58-c0373901c80e.png">

---

### Second conditional
https://github.com/pointfreeco/pointfreeco/blob/6da8acb583b22005053b617c265ded2a05cf722f/Sources/PointFree/Account/Account.swift#L321

<img width="399" alt="screen shot 2018-08-21 at 9 17 55 am" src="https://user-images.githubusercontent.com/13800855/44403928-a70ebf00-a523-11e8-8e45-593ee97e3b24.png">

**Comment by mbrandonw** [comment]
> What is the difference between Database.Subscription and Stripe.Subscription? Is one used mainly as a fallback?

The `Database.Subscription` type is the subscription data we hold in our actual postgres database, and the `Stripe.Subscription` is the data we get back from the Stripe API.

> In determining if a user is part of a team subscription, my first thought was to check the number of teammates, but that felt dirty. I am leaning towards something like:

That looks correct to me!

> Finally, I am not sure if simply adding the above isTeamSubscription helper to the ... check and just falling through to the next conditional will yield a desirable result.

Good catch, yeah that's not what we want.

> I am leaning towards something like adding the isTeamSubsubscription to this guard. Thoughts?

Yeah I think that's a better plan! This allows us to still render the `subscriptionPlanRows` view, which is the top-level overview of the subscription plan that all owners should see, but then omit team specific stuff where necessary. You probably want to upgrade `subscriptionTeamRow` to take the full `AccountData` instead of just the current user and teammates in order to do that `guard`.

I think you're close!
