### ISSUE TITLE
cmark.h not found

### ISSUE THREAD

**Issue by ZkHaider** [pointfreeco/pointfreeco#561]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/7844550/74595002-66e1ad00-4ff1-11ea-9e5b-31780fc8d133.png">

Steps to reproduce:

1.) Make sure `brew install cmark` is installed
2.) Run `brew services start postgresql`
3.) Clone pointfreeco via `git clone`
4.) Run `make db`
5.) Run `make`
6.) Run `swift package generate-xcodeproj`
7.) Hit CMD+B on PointfreeCo package to to get it to build. 

I'm assuming the PR to remove the `xcodeproj` building in the `Makefile` might have caused this?

**Comment by stephencelis** [comment]
@ZkHaider Are you running things in Xcode 11.3 or higher? You should be able to open the project as a SwiftPM project now and avoid the Xcode project (you can delete it) entirely.

**Comment by ZkHaider** [comment]
> @ZkHaider Are you running things in Xcode 11.3 or higher? You should be able to open the project as a SwiftPM project now and avoid the Xcode project (you can delete it) entirely.

Hey Stephen thanks for the direction :) love the work you guys have done at Pointfree and will try that and see if it works out ok.

**Comment by alexito4** [comment]
Hi @stephencelis I found the same issue and you're right is fine if you open the Package directly. But I've been having issues with that (that's why I tried the project generation path). Just as an FYI. 

For example the `OSS` compiler directive is not there and it tries to compile https://github.com/pointfreeco/pointfreeco/blob/09514fe24e3879679bc830da218db7b839c4bd87/Sources/PointFree/Bootstrap.swift#L97
I commented the private episodes part and the Server compiled but crashed at runtime. Now it seems to work, I think that executing the Runner target made it work? 

Now that the server is running I tired the tests, and there are a lot that fail. Some screenshoots seem to have a scrollbar on my machine. Other tests are because the environment is different ($ vs. £) but I guess that's expected.

<details><summary>screenshoots</summary>
<p>

![public png_2_7DDDFD62-36F2-4EFF-B836-5C486A57BDA1](https://user-images.githubusercontent.com/750912/75477184-2fcdad00-599c-11ea-989c-849c2a3c9ea7.png)
![public png_1_7DDDFD62-36F2-4EFF-B836-5C486A57BDA1](https://user-images.githubusercontent.com/750912/75477188-30feda00-599c-11ea-89e7-75cd13c73b0e.png)
![public png_3_7DDDFD62-36F2-4EFF-B836-5C486A57BDA1](https://user-images.githubusercontent.com/750912/75477167-2a706280-599c-11ea-9d93-ef3aaabbef62.png)

</p>
</details>

One thing I wanted to use is the playground. It seems like opening the package file directly doesn't include showing the playground. I dragged it manually to Xcode but doesn't seem like it has access to the modules. 

```
error: Episode Page.xcplaygroundpage:1:8: error: no such module 'HttpPipeline'
import HttpPipeline
....
```

**Comment by stephencelis** [comment]
Closed by #586.

**Comment by stephencelis** [comment]
@alexito4 Unfortunately playgrounds don't play nicely with SPM :( We're looking for solutions but haven't found any yet. We'd also like to experiment with Xcode previews, but they too don't seem ready yet.

**Comment by alexito4** [comment]
Thanks for the reply and the fix Stephen! ^^ Hopefully Xcode improves the situation soon.

**Comment by ZkHaider** [comment]
Coming back to this (was working with this project again recently 🙂) I found doing the following resulted in a successful build:

### 1. Build `.xcodeproj` file via Swift Package Manager:

<img src="https://user-images.githubusercontent.com/7844550/143666840-7d894711-c463-4bfe-8e58-ce711f0da993.png" width="650"/>

### 2. Link system libraries directly

<img src="https://user-images.githubusercontent.com/7844550/143666802-8ee9f51b-af87-4864-b69c-11504511489b.png" width="700"/>

### 2. Build `Pointfree-Package`:

<img src="https://user-images.githubusercontent.com/7844550/143666857-becbe138-c2a1-42f7-a967-b401b11fa397.png" width="800"/>


----

Some things to note, I am not sure how _hacky_ this solution is or if there is a better approach here (I tried `brew unlink cmark && brew link cmark` => this didn't work for me). Would be curious on thoughts.
